### ISSUE TITLE
Covid Dashboard: NYT geographic exceptions no longer returned by place-obs APIS

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/tools#2]
**NOTE: I'm not 100% sure this was the root of the problem, but I can't find any other explanation and I can't reproduce previous API responses.**

There was a change to the data returned when requesting the county population using the place-obs API, which caused the dashboard's server to crash. 

The following API requests would return a key/value for both geoId/3651000 and geoId/2938000. 

```
req_url="https://api.datacommons.org/bulk/place-obs",
req_json={"placeType": "County", "populationType": "Person", "observationDate": "2018"}.
```

The value contained the name of the city, but not the population.

Today, the API is suddenly no longer returning any key/value pairs for geoId/3651000 and geoId/2938000. So NaN is stored in the data frame as the name of the city.
During the calculations, when iterating over the names in the data frame, it encounters NaN as a name since no value was stored and the server crashes.

**Comment by edumorlom** [comment]
The temporary workaround to fix the issue was to manually write the data for the geographic exceptions.

        self.data.loc['geoId/3651000', 'state_dcid'] = "geoId/36"
        self.data.loc['geoId/3651000', 'state_name'] = "New York"
        self.data.loc['geoId/3651000', 'county_name'] = 'NYC'

The next step is to use a different API to retrieve the information for the cities since they are not counties.

**Comment by shifucun** [comment]
Per offline discussion, this is due to a data bug that changes the type of "New York" in at different version. To make it consistent, would suggest to not mingle place-obs and get_places_in api.
