### ISSUE TITLE
Covid Dashboard: Change in Stats REST API none return value causes crash

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/tools#3]
There was a breaking change to the return type of the Stats REST APIs that caused the server to crash with TypeError exception when trying to retrieve "data" from "None".

When making a request using the stats data commons REST APIs, if there was no data to return for a given dcid, it would drop the dcid from the response. Now, instead, it will return dcid->None, which caused issues when trying to read the data value.

Example of return type for dcid without a value:
![IMG_7122](https://user-images.githubusercontent.com/11444894/83722002-32c6e200-a60a-11ea-86f7-ee0372181df3.jpg)

Exception Message:
```
data = response[dcid]['data']
TypeError: 'NoneType' object is not subscriptable

```

**Comment by edumorlom** [comment]
The workaround is to try to retrieve the data, and if it fails due to TypeError exception because there is no data, continue to the next iteration.

```
for dcid in response:
   try:
      data = response[dcid]['data']
      data_holder[dcid] = data
   except TypeError:
         continue
```

**Comment by shifucun** [comment]
It is helpful to handle null/empty data in key value retrieval. In this case, you can do:

for dcid in response:
  if response[dcid] and 'data' in response[dcid]:
     xxx
  else:
    logging.error('missing data ...')
